### PR TITLE
Pull request for Angular CRUD App.

### PR DESCRIPTION
**Pull request by ElijahKyule**
**Description**
Aliens is a simple Angular application that allows  a user to add, update, delete and list aliens in a web page. The front-end interacts with Go REST API to facilitate GET, POST, PUT and DELETE rest methods. 
To test the application:
1.  Clone feature branch into your local environment,
2.  Unzip the cloned files.
3.  Open the unzipped files in your favorite IDE, preferably VS code.
4.  Navigate to the project directory using command line interface.
5.  Run the following commands:
6.  _npm install_
7.  _ng serve_
8.  launch the application in your browser through http://localhost:served-port
9. The following image shows the interface the Angular App

### CODE REVIEW

**Comment by Gabkings** [comment]
Fix the conflicts fast. Then we will continue.

**Review by Gabkings — COMMENTED** [review]
What does this PR do?
Description of Task to be completed?
How should this be manually tested?
Any background context you want to provide?
What are the relevant pivotal tracker stories?
Screenshots (if appropriate)
Questions:

#### Please answer the above quizzes. Once done let me know

**Comment by ElijahKyule** [comment]
**Roles of the Pull Request** 
This pull request entails a simple Angular application that allows a user to add, update, delete and list aliens in a web page. User can perform the aforementioned tasks by clicking an "add" button to add an alien, "update" button to update details of an existing alien, and a "delete" button to delete an existing alien.


**Tasks to be Completed**
The following tasks will be completed: creating a full flexed angular application with additional feature of manipulating posts, interactive validation of input data from user, and display of interactive and paginated tables.

**How to perform manual testing**
A live version of the application exists in Docker Hub. To pull the application to your local machine, kindly run the following series of commands:
1. _docker pull elijahkyule/alien_
2. _docker run -d -P --name alien elijahkyule/alien_
3. _docker port alien_
4. The application will launch in your browser _http://localhost:4200_

- To test the app's get functionality, the app should display a table containing aliens data.
image
- To test the app's add functionality, click on the "add" button, a bootstrap modal should be launched. Provide data by filling the input boxes. On clicking button data, the provided data should be submitted and a confirmation message pops up. 
Screenshot from 2022-03-06 10-12-52
- To test the app's update functionality, click on "edit" button associated with a particular alien of interest. A bootstrap modal should pop up, already populated with information of the selected alien. Update data in the input box of your interest. On clicking "update" button, the information should be submitted and a confirmation message displayed on your screen.
Screenshot from 2022-03-06 10-15-26
-  To test the app's delete functionality, click on "delete" button associated with the record to be deleted. A message should pop up to confirm the delete operation.


**Relevant background knowledge** 
Aliens is a simple Angular application that allows a user to add, update, delete and list aliens in a web page. Angular has proved to be an all-round and robust framework for building front-end of application. It uses TypeScript language, which is a strongly typed superscript  of Javascript. The front-end interacts with Go REST API to facilitate GET, POST, PUT and DELETE rest methods. To use Go REST you need to sign up to obtain an authorization token. The token is passed as an header in the API's rest methods. However, GET method doesn't have to be authorized unlike the other method. 
Docker has also been used to containerize the application for ease of portability and conservation of computing resources.

@Gabkings

**Comment by ElijahKyule** [comment]
Hello. I've created another comment addressing your concerns. Kindly find
some time to review it.

**Comment by Gabkings** [comment]
You can merge into the develop branch

**Comment by Gabkings** [comment]
I can you have now master the git workflow, raising well documented PR's

**Pull request merged**
